syseng_back/syseng_back.Web/Controllers/HomeController.cs
using AutoMapper;
using syseng_back.BLL.DTO;
using syseng_back.BLL.Interfaces;
using syseng_back.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace syseng_back.Web.Controllers
{
    public class homeController : Controller
    {
        IArticleService _articleService;
        IProjectService _projectService;
        ILeadService _leadService;

        public homeController(IArticleService articleService, IProjectService projectService, ILeadService leadService)
        {
            this._articleService = articleService;
            this._projectService = projectService;
            this._leadService = leadService;
        }

        public ActionResult index()
        {
            IEnumerable<ArticleDTO> articlesDtos = _articleService.GetArticles().Take(3);
            Mapper.Initialize(c => c.CreateMap<ArticleDTO, ArticleViewModel>());
            var articles = Mapper.Map<IEnumerable<ArticleDTO>, List<ArticleViewModel>>(articlesDtos);
            ViewBag.Articles = articles;

            IEnumerable<ProjectDTO> projectsDtos = _projectService.GetProjects();
            Mapper.Initialize(c => c.CreateMap<ProjectDTO, ProjectViewModel>());
            var projects = Mapper.Map<IEnumerable<ProjectDTO>, List<ProjectViewModel>>(projectsDtos);
            ViewBag.Projects = projects;

            return View();
        }

        public ActionResult articles()
        {
            IEnumerable<ArticleDTO> articlesDtos = _articleService.GetArticles();
            Mapper.Initialize(c => c.CreateMap<ArticleDTO, ArticleViewModel>());
            var articles = Mapper.Map<IEnumerable<ArticleDTO>, List<ArticleViewModel>>(articlesDtos);
            ViewBag.Articles = articles;
            return View();
        }

        public ActionResult article(int id)
        {
            ArticleDTO articleDtos = _articleService.GetArticle(id);
            Mapper.Initialize(c => c.CreateMap<ArticleDTO, ArticleViewModel>());
            var article = Mapper.Map<ArticleDTO, ArticleViewModel>(articleDtos);
            ViewBag.Article = article;
            return View();
        }

        public ActionResult project(int id)
        {
            ProjectDTO projectDtos = _projectService.GetProject(id);
            Mapper.Initialize(c => c.CreateMap<ProjectDTO, ProjectViewModel>());
            var project = Mapper.Map<ProjectDTO, ProjectViewModel>(projectDtos);
            ViewBag.Project = project;
            return View();
        }

        public ActionResult projects()
        {
            IEnumerable<ProjectDTO> projectsDtos = _projectService.GetProjects();
            Mapper.Initialize(c => c.CreateMap<ProjectDTO, ProjectViewModel>());
            var projects = Mapper.Map<IEnumerable<ProjectDTO>, List<ProjectViewModel>>(projectsDtos);
            ViewBag.Projects = projects;
            return View();
        }

        public ActionResult automation()
        {
            return View();
        }

        public ActionResult waterclean()
        {
            return View();
        }

        public ActionResult contacts()
        {
            return View();
        }

        [HttpPost]
        public JsonResult mail(LeadViewModel model)
        {
            string response = "Ok";
            try
            {
                Mapper.Initialize(c => c.CreateMap<LeadViewModel, LeadDTO>());
                var lead = Mapper.Map<LeadViewModel, LeadDTO>(model);
                _leadService.AddLead(lead);
            }
            catch
            {
                return Json("No");
            }

            return Json(response);
        }
    }
}

syseng_back/syseng_back.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

syseng_back/syseng_back.Web/Views/Shared/_LayoutArticles.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/core")
    @Styles.Render("~/Content/articles")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav id="nav" class="navbar navbar-default navbar-fixed">
        <div class="container-fluid">
            <div class="navbar-header">
                <button style="border-radius: 0px;" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img alt="Brand" src="~/Content/images/logo3.png" width="35" height="35">
                </a>
                <h4 style="color:white;">ООО "Системная инженерия"</h4>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul id="ul" class="nav navbar-nav navbar-right mainheader">
                    <li>@Html.ActionLink("Главная", "index", "home")</li>
                    <li>@Html.ActionLink("Проекты", "projects", "home")</li>
                    <li>@Html.ActionLink("Статьи", "articles", "home")</li>
                    <li>@Html.ActionLink("Автоматизация", "automation", "home")</li>
                    <li>@Html.ActionLink("Водоочистка", "waterclean", "home")</li>
                    <li>@Html.ActionLink("Контакты", "contacts", "home")</li>
                </ul>

            </div>
        </div>
    </nav>

    @RenderBody()

    <footer>
        <div class="col-md-12 body">
            <div class="col-md-1"></div>

            <div class="col-md-3 block bloackbl">
                <h2>Системы водоочистки</h2>
                <p>Создание эффективных систем водоснабжения предприятий и населённых пунктов</p>
            </div>

            <div class="col-md-3 block">
                <h2>Контакты</h2>
                <p><span class="glyphicon glyphicon-earphone"></span> +375 44 465 86 10</p>
                <p><span class="glyphicon glyphicon-earphone"></span> +375 44 465 73 14</p>
                <p><span class="glyphicon glyphicon-envelope"></span> p.burik@pinsk.1ak.by</p>
                <p><span class="glyphicon glyphicon-home"></span> Республика Беларусь, г. Пинск, ул. Брестская д. 72</p>
            </div>

            <div class="col-md-3 block bloackbl">
                <h2>Автоматизация</h2>
                <p>Разработка программного обеспечения для управления промышленными комплексами и системами</p>
            </div>
            <div class="col-md-1"></div>

            <div class="container">
                <ul id="ul" class="nav navbar-nav  footul">
                    <li>@Html.ActionLink("Главная", "index", "home")</li>
                    <li>@Html.ActionLink("Проекты", "projects", "home")</li>
                    <li>@Html.ActionLink("Статьи", "articles", "home")</li>
                    <li>@Html.ActionLink("Автоматизация", "automation", "home")</li>
                    <li>@Html.ActionLink("Водоочистка", "waterclean", "home")</li>
                    <li>@Html.ActionLink("Контакты", "contacts", "home")</li>
                </ul>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/mail")
</body>
</html>

syseng_back/syseng_back.Web/Views/Shared/_LayoutFront.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/core")
    @Styles.Render("~/Content/index")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav id="nav" class="navbar navbar-default navbar-fixed">
        <div class="container-fluid">
            <div class="navbar-header">
                <button style="border-radius: 0px;" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img alt="Brand" src="~/Content/images/logo3.png" width="35" height="35">
                </a>
                <h4 style="color:white;">ООО "Системная инженерия"</h4>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul id="ul" class="nav navbar-nav navbar-right mainheader">
                    <li>@Html.ActionLink("Главная", "index", "home")</li>
                    <li>@Html.ActionLink("Проекты", "projects", "home")</li>
                    <li>@Html.ActionLink("Статьи", "articles", "home")</li>
                    <li>@Html.ActionLink("Автоматизация", "automation", "home")</li>
                    <li>@Html.ActionLink("Водоочистка", "waterclean", "home")</li>
                    <li>@Html.ActionLink("Контакты", "contacts", "home")</li>
                </ul>

            </div>
        </div>
    </nav>

    @RenderBody()

    <footer>
        <div class="col-md-12 body">
            <div class="col-md-1"></div>

            <div class="col-md-3 block bloackbl">
                <h2>Системы водоочистки</h2>
                <p>Создание эффективных систем водоснабжения предприятий и населённых пунктов</p>
            </div>

            <div class="col-md-3 block">
                <h2>Контакты</h2>
                <p><span class="glyphicon glyphicon-earphone"></span> +375 44 465 86 10</p>
                <p><span class="glyphicon glyphicon-earphone"></span> +375 44 465 73 14</p>
                <p><span class="glyphicon glyphicon-envelope"></span> p.burik@pinsk.1ak.by</p>
                <p><span class="glyphicon glyphicon-home"></span> Республика Беларусь, г. Пинск, ул. Брестская д. 72</p>
            </div>

            <div class="col-md-3 block bloackbl">
                <h2>Автоматизация</h2>
                <p>Разработка программного обеспечения для управления промышленными комплексами и системами</p>
            </div>
            <div class="col-md-1"></div>

            <div class="container">
                <ul id="ul" class="nav navbar-nav  footul">
                    <li>@Html.ActionLink("Главная", "index", "home")</li>
                    <li>@Html.ActionLink("Проекты", "projects", "home")</li>
                    <li>@Html.ActionLink("Статьи", "articles", "home")</li>
                    <li>@Html.ActionLink("Автоматизация", "automation", "home")</li>
                    <li>@Html.ActionLink("Водоочистка", "waterclean", "home")</li>
                    <li>@Html.ActionLink("Контакты", "contacts", "home")</li>
                </ul>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/mail")
</body>
</html>